version: "3.8"
services:
  web:
    build: web/.
    ports:
      - "80:80"
    environment:
      - PGHOST
      - PGUSER
      - PGDATABASE
      - PGPASSWORD
      - PGPORT
  db:
    build: db/.
    environment:
      - POSTGRES_DB
      - POSTGRES_USER
      - POSTGRES_PASSWORD